-- ============================================================
--  Chrysos POC  ·  source system schema
--  Target: PostgreSQL on Amazon RDS
--
--  This database stands in for a customer lab's operational
--  system. Glue extracts FROM here. Nothing about the pipeline
--  is stored in here, because in real life Chrysos would not
--  own this database.
-- ============================================================

BEGIN;

DROP TABLE IF EXISTS assay_measurement;
DROP TABLE IF EXISTS machine;
DROP FUNCTION IF EXISTS set_updated_at();

-- ------------------------------------------------------------
--  machine  ·  the fleet.  60 rows, changes rarely.
-- ------------------------------------------------------------
CREATE TABLE machine (
    machine_id          integer       PRIMARY KEY,
    machine_code        text          NOT NULL UNIQUE,
    site_name           text          NOT NULL,
    country             text          NOT NULL,
    customer            text          NOT NULL,
    utc_offset_hours    numeric(4,1)  NOT NULL,
    target_utilisation  numeric(4,3)  NOT NULL,
    installed_date      date          NOT NULL,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now()
);

-- ------------------------------------------------------------
--  assay_measurement
--  Grain: ONE ROW PER MEASUREMENT, PER ELEMENT.
--  One jar measured for gold and silver produces two rows.
-- ------------------------------------------------------------
CREATE TABLE assay_measurement (
    measurement_id      bigint        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sample_id           text          NOT NULL,
    machine_id          integer       NOT NULL REFERENCES machine(machine_id),
    customer            text          NOT NULL,
    element             text          NOT NULL,
    value_ppm           numeric(12,4),
    uncertainty_ppm     numeric(12,4),
    measure_seconds     integer       NOT NULL,
    assay_mode          text          NOT NULL,
    sample_type         text          NOT NULL,
    crm_code            text,
    crm_certified_ppm   numeric(12,4),
    below_detection     boolean       NOT NULL DEFAULT false,
    started_utc         timestamptz   NOT NULL,
    created_at          timestamptz   NOT NULL DEFAULT now(),
    updated_at          timestamptz   NOT NULL DEFAULT now(),

    CONSTRAINT ck_element     CHECK (element     IN ('gold','silver')),
    CONSTRAINT ck_sample_type CHECK (sample_type IN ('customer','crm','blank','repeat')),
    CONSTRAINT ck_assay_mode  CHECK (assay_mode  IN ('gold_tuned','silver_tuned')),
    -- a certified value exists only for a certified jar
    CONSTRAINT ck_crm_pairing CHECK (
        (sample_type = 'crm' AND crm_code IS NOT NULL AND crm_certified_ppm IS NOT NULL)
     OR (sample_type <> 'crm' AND crm_code IS NULL AND crm_certified_ppm IS NULL)
    )
);

-- ------------------------------------------------------------
--  THE WATERMARK GUARD
--
--  updated_at is what the incremental load reads. If any code
--  path changes a row and forgets to move updated_at, that row
--  becomes invisible to the pipeline permanently. So the
--  database maintains it, not the application.
-- ------------------------------------------------------------
CREATE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_machine_updated_at
    BEFORE UPDATE ON machine
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_assay_measurement_updated_at
    BEFORE UPDATE ON assay_measurement
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ------------------------------------------------------------
--  INDEXES
--
--  idx_assay_updated_at is the one the pipeline depends on.
--  Without it, every incremental run scans the whole table to
--  find the few rows that changed, and the watermark saves
--  nothing.
-- ------------------------------------------------------------
CREATE INDEX idx_assay_updated_at      ON assay_measurement (updated_at);
CREATE INDEX idx_machine_updated_at    ON machine           (updated_at);
CREATE INDEX idx_assay_machine_started ON assay_measurement (machine_id, started_utc);
CREATE INDEX idx_assay_crm             ON assay_measurement (sample_type, element, started_utc)
                                          WHERE sample_type = 'crm';

COMMIT;
